/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Library.Objetos;
import ViewModels.ClientesVM;
import ViewModels.ConfigurationVM;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class Sistema extends javax.swing.JFrame {

    private final List<JRadioButton> _radio;

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        //Codigo de Configuracion
        _radio = new ArrayList();
        _radio.add(RadioButtonDollar);
        _radio.add(RadioButtonSol);
        _radio.add(RadioButtonPeso);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tabb_Principal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        B_Cliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        TabbedPaneCliente1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        tf_ap_CI = new javax.swing.JTextField();
        Lb_Cli_Ap = new javax.swing.JLabel();
        tf_Ci = new javax.swing.JTextField();
        Lb_Cli_Mail = new javax.swing.JLabel();
        tf_Nom_CI = new javax.swing.JTextField();
        Lb_Cli_Nom = new javax.swing.JLabel();
        tf_mail_CI = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        Lb_Img_Cli = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lb_Cli_ID = new javax.swing.JLabel();
        Lb_Cli_Tlf = new javax.swing.JLabel();
        tf_tlf_CI = new javax.swing.JTextField();
        tf_dir_CI = new javax.swing.JTextField();
        Lb_Cli_Dir = new javax.swing.JLabel();
        ChB_Credito = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        lbReport_Nombre = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Lb_Cli_Nom3 = new javax.swing.JLabel();
        lb_ClienteDeuda = new javax.swing.JLabel();
        Lb_Cli_Nom5 = new javax.swing.JLabel();
        lb_ClienteUltimoPago = new javax.swing.JLabel();
        lb_CliendePago1 = new javax.swing.JLabel();
        lb_ClienteTicket = new javax.swing.JLabel();
        Lb_Cli_Nom6 = new javax.swing.JLabel();
        lb_ClienteFechaPago = new javax.swing.JLabel();
        Lb_Cli_Nom8 = new javax.swing.JLabel();
        lb_ClienteCuotaMes = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lb_FechaIntereses = new javax.swing.JLabel();
        Lb_Cli_Nom9 = new javax.swing.JLabel();
        lb_ClienteIntereses = new javax.swing.JLabel();
        Lb_Cli_Nom10 = new javax.swing.JLabel();
        Lb_Cli_Nom11 = new javax.swing.JLabel();
        lb_ClienteCuotas = new javax.swing.JLabel();
        Lb_Cli_Nom12 = new javax.swing.JLabel();
        txf_clienteCuotas = new javax.swing.JTextField();
        lb_ClienteTicketIntereses = new javax.swing.JLabel();
        lb_CliendePago2 = new javax.swing.JLabel();
        Lb_Cli_Nom13 = new javax.swing.JLabel();
        lb_ClienteInteresesPago = new javax.swing.JLabel();
        lb_ReportsPagos = new javax.swing.JLabel();
        txf_clientePagos = new javax.swing.JTextField();
        RadioButton_Cuotas = new javax.swing.JRadioButton();
        RadioButton_Intereses = new javax.swing.JRadioButton();
        Btn_Agg = new javax.swing.JButton();
        Btn_Cli = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Table_clientes_Report1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_clientes =     Table_clientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_clientes_Report =     Table_clientes_Report = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Lb_Cli_Nom1 = new javax.swing.JLabel();
        SpinnerPaginas_Clientes = new javax.swing.JSpinner();
        Btn_Cliente_Paginas1 = new javax.swing.JButton();
        Btn_Cliente_Paginas2 = new javax.swing.JButton();
        Btn_Cliente_Paginas4 = new javax.swing.JButton();
        Btn_Cliente_Paginas3 = new javax.swing.JButton();
        lb_Cliente_Paginas = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        RadioButtonDollar = new javax.swing.JRadioButton();
        RadioButtonSol = new javax.swing.JRadioButton();
        RadioButtonPeso = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Btn_Cliente = new javax.swing.JButton();
        Btn_Ventas = new javax.swing.JButton();
        Btn_Configuracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PUNTO DE VENTA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo-tienda.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
            .addComponent(jLabel2)
        );

        Tabb_Principal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        Tabb_Principal.addTab("Ventas", jPanel2);

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 106, 124));
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 106, 124));
        jLabel4.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(B_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPaneCliente1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneCliente1StateChanged(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tf_ap_CI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_ap_CIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_ap_CIKeyTyped(evt);
            }
        });

        Lb_Cli_Ap.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Ap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Ap.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Ap.setText("Apellido");

        tf_Ci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_CiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_CiKeyTyped(evt);
            }
        });

        Lb_Cli_Mail.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Mail.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Mail.setText("Email");

        tf_Nom_CI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_Nom_CIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_Nom_CIKeyTyped(evt);
            }
        });

        Lb_Cli_Nom.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Nom.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom.setText("Nombre");

        tf_mail_CI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_mail_CIKeyReleased(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lb_Img_Cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo_persona.png"))); // NOI18N
        Lb_Img_Cli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lb_Img_Cli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lb_Img_Cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lb_Img_CliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Img_Cli, javax.swing.GroupLayout.PREFERRED_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Img_Cli, javax.swing.GroupLayout.PREFERRED_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 106, 124));
        jLabel5.setText("Informacion del cliente");

        Lb_Cli_ID.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_ID.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_ID.setText("CI");

        Lb_Cli_Tlf.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Tlf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Tlf.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Tlf.setText("Telefono");

        tf_tlf_CI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_tlf_CIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_tlf_CIKeyTyped(evt);
            }
        });

        tf_dir_CI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_dir_CIKeyReleased(evt);
            }
        });

        Lb_Cli_Dir.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Dir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Dir.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Dir.setText("Direccion");

        ChB_Credito.setText("Credito");
        ChB_Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChB_CreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(107, 107, 107))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_ap_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lb_Cli_ID)
                                .addComponent(tf_Ci, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(Lb_Cli_Ap)
                                .addComponent(Lb_Cli_Tlf)
                                .addComponent(tf_tlf_CI))
                            .addComponent(ChB_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Cli_Dir)
                            .addComponent(Lb_Cli_Mail)
                            .addComponent(tf_mail_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Nom_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dir_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lb_Cli_Nom)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Cli_ID)
                    .addComponent(Lb_Cli_Nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Nom_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Cli_Mail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lb_Cli_Ap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ap_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_mail_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Cli_Tlf)
                    .addComponent(Lb_Cli_Dir))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tlf_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dir_CI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ChB_Credito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPaneCliente1.addTab("Registro de Clientes", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        lbReport_Nombre.setBackground(new java.awt.Color(70, 106, 124));
        lbReport_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbReport_Nombre.setForeground(new java.awt.Color(70, 106, 124));
        lbReport_Nombre.setText("Nombre Cliente");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Lb_Cli_Nom3.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom3.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom3.setText("Deuda");

        lb_ClienteDeuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteDeuda.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteDeuda.setText(".");

        Lb_Cli_Nom5.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom5.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom5.setText("Pago");

        lb_ClienteUltimoPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteUltimoPago.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteUltimoPago.setText(".");

        lb_CliendePago1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_CliendePago1.setForeground(new java.awt.Color(187, 187, 187));
        lb_CliendePago1.setText("Ticket:");

        lb_ClienteTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteTicket.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteTicket.setText(".");

        Lb_Cli_Nom6.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Nom6.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom6.setText("Fecha del Pago");

        lb_ClienteFechaPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_ClienteFechaPago.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteFechaPago.setText(".");

        Lb_Cli_Nom8.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Nom8.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom8.setText("Cuotas por Mes");

        lb_ClienteCuotaMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteCuotaMes.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteCuotaMes.setText(".");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Cli_Nom3)
                    .addComponent(lb_ClienteDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Cli_Nom6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ClienteFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Cli_Nom5)
                            .addComponent(lb_ClienteUltimoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_ClienteCuotaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Cli_Nom8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_CliendePago1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ClienteTicket))
                .addGap(20, 20, 20))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Cli_Nom3)
                    .addComponent(Lb_Cli_Nom5)
                    .addComponent(lb_CliendePago1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ClienteDeuda)
                    .addComponent(lb_ClienteUltimoPago)
                    .addComponent(lb_ClienteTicket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Cli_Nom6)
                    .addComponent(Lb_Cli_Nom8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ClienteFechaPago)
                    .addComponent(lb_ClienteCuotaMes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lb_FechaIntereses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_FechaIntereses.setForeground(new java.awt.Color(70, 106, 124));
        lb_FechaIntereses.setText(".");

        Lb_Cli_Nom9.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom9.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom9.setText("Intereses");

        lb_ClienteIntereses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteIntereses.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteIntereses.setText(".");

        Lb_Cli_Nom10.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom10.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom10.setText("Cuotas");

        Lb_Cli_Nom11.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom11.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom11.setText("Fecha del pago");

        lb_ClienteCuotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteCuotas.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteCuotas.setText(".");

        Lb_Cli_Nom12.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom12.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom12.setText("Total Intereses");

        txf_clienteCuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txf_clienteCuotasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_clienteCuotasKeyTyped(evt);
            }
        });

        lb_ClienteTicketIntereses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteTicketIntereses.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteTicketIntereses.setText(".");

        lb_CliendePago2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_CliendePago2.setForeground(new java.awt.Color(187, 187, 187));
        lb_CliendePago2.setText("Ticket:");

        Lb_Cli_Nom13.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lb_Cli_Nom13.setForeground(new java.awt.Color(187, 187, 187));
        Lb_Cli_Nom13.setText("Total a Pagar");

        lb_ClienteInteresesPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ClienteInteresesPago.setForeground(new java.awt.Color(70, 106, 124));
        lb_ClienteInteresesPago.setText(".");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Cli_Nom9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ClienteIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_FechaIntereses, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Cli_Nom11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(Lb_Cli_Nom12)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_Cli_Nom13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(txf_clienteCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_ClienteInteresesPago, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Cli_Nom10)
                            .addComponent(lb_ClienteCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_CliendePago2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_ClienteTicketIntereses))))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Cli_Nom9)
                            .addComponent(Lb_Cli_Nom10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_ClienteIntereses)
                            .addComponent(lb_ClienteCuotas)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_CliendePago2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_ClienteTicketIntereses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Cli_Nom11)
                    .addComponent(Lb_Cli_Nom12)
                    .addComponent(Lb_Cli_Nom13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_clienteCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_FechaIntereses)
                    .addComponent(lb_ClienteInteresesPago))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lb_ReportsPagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_ReportsPagos.setForeground(new java.awt.Color(70, 106, 124));
        lb_ReportsPagos.setText("Ingrese el Pago");

        txf_clientePagos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txf_clientePagosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_clientePagosKeyTyped(evt);
            }
        });

        buttonGroup1.add(RadioButton_Cuotas);
        RadioButton_Cuotas.setText("Cuotas");
        RadioButton_Cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_CuotasActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButton_Intereses);
        RadioButton_Intereses.setText("Intereses");
        RadioButton_Intereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_InteresesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(RadioButton_Cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(RadioButton_Intereses, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(lbReport_Nombre))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_ReportsPagos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txf_clientePagos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbReport_Nombre)
                .addGap(23, 23, 23)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton_Cuotas)
                    .addComponent(RadioButton_Intereses))
                .addGap(18, 18, 18)
                .addComponent(lb_ReportsPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txf_clientePagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPaneCliente1.addTab("Pagos y Reportes", jPanel7);

        Btn_Agg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        Btn_Agg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Agg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AggActionPerformed(evt);
            }
        });

        Btn_Cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancelar.png"))); // NOI18N
        Btn_Cli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCliente1)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Btn_Cli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(Btn_Agg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Cli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Agg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_clientes_Report1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Table_clientes_Report1StateChanged(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Table_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_clientesMouseClicked(evt);
            }
        });
        Table_clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_clientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table_clientes);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        Table_clientes_Report1.addTab("Lista de Clientes", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));

        Table_clientes_Report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_clientes_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_clientes_ReportMouseClicked(evt);
            }
        });
        Table_clientes_Report.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_clientes_ReportKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Table_clientes_Report);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        Table_clientes_Report1.addTab("Pagos y Reportes", jPanel11);

        Lb_Cli_Nom1.setBackground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lb_Cli_Nom1.setForeground(new java.awt.Color(70, 106, 124));
        Lb_Cli_Nom1.setText("Registro por Paginas");

        SpinnerPaginas_Clientes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerPaginas_ClientesStateChanged(evt);
            }
        });

        Btn_Cliente_Paginas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leftp2.png"))); // NOI18N
        Btn_Cliente_Paginas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cliente_Paginas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cliente_Paginas1ActionPerformed(evt);
            }
        });

        Btn_Cliente_Paginas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leftp1.png"))); // NOI18N
        Btn_Cliente_Paginas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cliente_Paginas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cliente_Paginas2ActionPerformed(evt);
            }
        });

        Btn_Cliente_Paginas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rigth2.png"))); // NOI18N
        Btn_Cliente_Paginas4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cliente_Paginas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cliente_Paginas4ActionPerformed(evt);
            }
        });

        Btn_Cliente_Paginas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rigt1.png"))); // NOI18N
        Btn_Cliente_Paginas3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cliente_Paginas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cliente_Paginas3ActionPerformed(evt);
            }
        });

        lb_Cliente_Paginas.setBackground(new java.awt.Color(70, 106, 124));
        lb_Cliente_Paginas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Cliente_Paginas.setForeground(new java.awt.Color(70, 106, 124));
        lb_Cliente_Paginas.setText("Paginas");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(SpinnerPaginas_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296)
                        .addComponent(Btn_Cliente_Paginas1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Btn_Cliente_Paginas2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(Btn_Cliente_Paginas3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(Btn_Cliente_Paginas4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(Lb_Cli_Nom1)
                        .addGap(415, 415, 415)
                        .addComponent(lb_Cliente_Paginas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Table_clientes_Report1)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Table_clientes_Report1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Cli_Nom1)
                            .addComponent(lb_Cliente_Paginas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpinnerPaginas_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_Cliente_Paginas2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Cliente_Paginas1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Cliente_Paginas4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Cliente_Paginas3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Tabb_Principal.addTab("Clientes", jPanel3);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 106, 124));
        jLabel6.setText("Configuraciones");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(RadioButtonDollar);
        RadioButtonDollar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonDollar.setText("$");
        RadioButtonDollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonDollarActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonSol);
        RadioButtonSol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonSol.setText("Sol");
        RadioButtonSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSolActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonPeso);
        RadioButtonPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonPeso.setText("Peso");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 106, 124));
        jLabel7.setText("Tipo de Moneda");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonDollar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonSol, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(RadioButtonDollar)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonSol)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonPeso)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1096, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Tabb_Principal.addTab("Config", jPanel15);

        Btn_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/people.png"))); // NOI18N
        Btn_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClienteActionPerformed(evt);
            }
        });

        Btn_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoping.png"))); // NOI18N
        Btn_Ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Btn_Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/settings.png"))); // NOI18N
        Btn_Configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabb_Principal)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Btn_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tabb_Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClienteActionPerformed
        // TODO add your handling code here:
        ArrayList<JLabel> label = new ArrayList();
        label.add(Lb_Cli_ID);
        label.add(Lb_Cli_Nom);
        label.add(Lb_Cli_Ap);
        label.add(Lb_Cli_Mail);
        label.add(Lb_Cli_Tlf);
        label.add(Lb_Cli_Dir);
        label.add(Lb_Img_Cli);
        label.add(lb_Cliente_Paginas);
        //7 
        label.add(lbReport_Nombre);
        label.add(lb_ClienteDeuda);
        label.add(lb_ClienteUltimoPago);
        label.add(lb_ClienteTicket);
        label.add(lb_ClienteFechaPago);
        label.add(lb_ClienteCuotaMes);
        //
        label.add(lb_ClienteIntereses);
        label.add(lb_ClienteCuotas);
        label.add(lb_ClienteTicketIntereses);
        label.add(lb_FechaIntereses);
        label.add(lb_ClienteInteresesPago);
        label.add(lb_ReportsPagos);
        
        ArrayList<JTextField> textField = new ArrayList();
        textField.add(tf_Ci);
        textField.add(tf_Nom_CI);
        textField.add(tf_ap_CI);
        textField.add(tf_mail_CI);
        textField.add(tf_tlf_CI);
        textField.add(tf_dir_CI);
        
        textField.add(txf_clientePagos);
        textField.add(txf_clienteCuotas);
        Object[] objects = {
            ChB_Credito,
            Table_clientes,
            SpinnerPaginas_Clientes,
            Table_clientes_Report,
            RadioButton_Cuotas,
            RadioButton_Intereses
                
        };
        try {
            cliente = new ClientesVM(objects, label, textField);
        } catch (SQLException ex) {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }

        Tabb_Principal.setSelectedIndex(1);
        Btn_Cliente.setEnabled(false);
        Btn_Configuracion.setEnabled(true);
        RadioButton_Cuotas.setSelected(true);
        txf_clienteCuotas.setEnabled(false);
    }//GEN-LAST:event_Btn_ClienteActionPerformed
// <editor-fold defaultstate="collapsed" desc="CODIGO DE CLIENTE"> 
    private ClientesVM cliente;

    private void Btn_AggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AggActionPerformed
        // TODO add your handling code here:
        switch (TabbedPaneCliente1.getSelectedIndex()) {
            case 0:
               cliente.RegistrarCliente();
                break;
            case 1:
            {
                try {
                    cliente.EjecutarPago();
                } catch (SQLException ex) {
                    Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;

        }
    }//GEN-LAST:event_Btn_AggActionPerformed

    private void Btn_CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CliActionPerformed
        // TODO add your handling code here:
        cliente.restablecer();
    }//GEN-LAST:event_Btn_CliActionPerformed

    private void Lb_Img_CliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_Img_CliMouseClicked
        // TODO add your handling code here:
        Objetos.uploadImage.CargarImagen(Lb_Img_Cli);
    }//GEN-LAST:event_Lb_Img_CliMouseClicked

    private void tf_CiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_CiKeyReleased
        // TODO add your handling code here:
        if (tf_Ci.getText().equals("")) {
            Lb_Cli_ID.setForeground(new Color(102, 102, 102));
        } else {
            Lb_Cli_ID.setText("CI");
            Lb_Cli_ID.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_tf_CiKeyReleased

    private void tf_CiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_CiKeyTyped
        // TODO add your handling code here:
        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_tf_CiKeyTyped

    private void tf_Nom_CIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Nom_CIKeyReleased
        // TODO add your handling code here:
        if (tf_Nom_CI.getText().equals("")) {
            Lb_Cli_Nom.setForeground(new Color(102, 102, 102));
        } else {
            Lb_Cli_Nom.setText("Nombre");
            Lb_Cli_Nom.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_tf_Nom_CIKeyReleased

    private void tf_Nom_CIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Nom_CIKeyTyped
        // TODO add your handling code here:
        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_tf_Nom_CIKeyTyped

    private void tf_ap_CIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ap_CIKeyReleased
        // TODO add your handling code here:
        if (tf_ap_CI.getText().equals("")) {
            Lb_Cli_Ap.setForeground(new Color(102, 102, 102));
        } else {
            Lb_Cli_Ap.setText("Apellido");
            Lb_Cli_Ap.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_tf_ap_CIKeyReleased

    private void tf_ap_CIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ap_CIKeyTyped
        // TODO add your handling code here:
        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_tf_ap_CIKeyTyped

    private void tf_mail_CIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_mail_CIKeyReleased
        // TODO add your handling code here:
        if (tf_mail_CI.getText().equals("")) {
            Lb_Cli_Mail.setForeground(new Color(102, 102, 102));
        } else {
            Lb_Cli_Mail.setText("Email");
            Lb_Cli_Mail.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_tf_mail_CIKeyReleased

    private void tf_tlf_CIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_tlf_CIKeyReleased
        // TODO add your handling code here:
        if (tf_tlf_CI.getText().equals("")) {
            Lb_Cli_Tlf.setForeground(new Color(102, 102, 102));
        } else {
            Lb_Cli_Tlf.setText("Telefono");
            Lb_Cli_Tlf.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_tf_tlf_CIKeyReleased

    private void tf_tlf_CIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_tlf_CIKeyTyped
        // TODO add your handling code here:
        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_tf_tlf_CIKeyTyped

    private void tf_dir_CIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dir_CIKeyReleased
        // TODO add your handling code here:
        if (tf_dir_CI.getText().equals("")) {
            Lb_Cli_Dir.setForeground(new Color(102, 102, 102));
        } else {
            Lb_Cli_Dir.setText("Direccion");
            Lb_Cli_Dir.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_tf_dir_CIKeyReleased

    private void ChB_CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChB_CreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChB_CreditoActionPerformed

    private void Btn_Cliente_Paginas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cliente_Paginas1ActionPerformed
        // TODO add your handling code here:
        cliente.Paginador("Primero");
    }//GEN-LAST:event_Btn_Cliente_Paginas1ActionPerformed

    private void Btn_Cliente_Paginas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cliente_Paginas2ActionPerformed
        // TODO add your handling code here:
        cliente.Paginador("Anterior");
    }//GEN-LAST:event_Btn_Cliente_Paginas2ActionPerformed

    private void Btn_Cliente_Paginas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cliente_Paginas4ActionPerformed
        // TODO add your handling code here:
        cliente.Paginador("Ultimo");
    }//GEN-LAST:event_Btn_Cliente_Paginas4ActionPerformed

    private void Btn_Cliente_Paginas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cliente_Paginas3ActionPerformed
        // TODO add your handling code here:
        cliente.Paginador("Siguiente");
    }//GEN-LAST:event_Btn_Cliente_Paginas3ActionPerformed

    private void SpinnerPaginas_ClientesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerPaginas_ClientesStateChanged
        // TODO add your handling code here:
        cliente.Registro_Paginas();
    }//GEN-LAST:event_SpinnerPaginas_ClientesStateChanged

    private void Table_clientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_clientesKeyReleased
        // TODO add your handling code here:
        if (Table_clientes.getSelectedRows().length > 0) {
            cliente.GetCliente();
        }
    }//GEN-LAST:event_Table_clientesKeyReleased

    private void Table_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_clientesMouseClicked
        // TODO add your handling code here:
        if (Table_clientes.getSelectedRows().length > 0) {
            cliente.GetCliente();
        }
    }//GEN-LAST:event_Table_clientesMouseClicked

    private void TabbedPaneCliente1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneCliente1StateChanged
        // TODO add your handling code here:
        switch (TabbedPaneCliente1.getSelectedIndex()) {
            case 0:
                if (Table_clientes_Report1.getSelectedIndex() > 0) {
                    Table_clientes_Report1.setSelectedIndex(0);
                    cliente.seccion = 1;
                    cliente.Registro_Paginas();
                }
                break;
            case 1:
                cliente.seccion = 2;
                Table_clientes_Report1.setSelectedIndex(1);
                cliente.Registro_Paginas();
                break;
        }
    }//GEN-LAST:event_TabbedPaneCliente1StateChanged

    private void Table_clientes_Report1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Table_clientes_Report1StateChanged
        // TODO add your handling code here:
        switch (Table_clientes_Report1.getSelectedIndex()) {
            case 0:
                if (TabbedPaneCliente1.getSelectedIndex() > 0) {
                    TabbedPaneCliente1.setSelectedIndex(0);
                    cliente.seccion = 1;
                    cliente.Registro_Paginas();
                }
                break;
            case 1:
                cliente.seccion = 2;
                TabbedPaneCliente1.setSelectedIndex(1);
                cliente.Registro_Paginas();
                break;
        }
    }//GEN-LAST:event_Table_clientes_Report1StateChanged

    private void Table_clientes_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_clientes_ReportMouseClicked
        // TODO add your handling code here:
        if (Table_clientes_Report.getSelectedRows().length > 0) {
            cliente.GetReportCliente();
            cliente.CuotasIntereses();
        }
    }//GEN-LAST:event_Table_clientes_ReportMouseClicked

    private void Table_clientes_ReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_clientes_ReportKeyReleased
        // TODO add your handling code here:
        if (Table_clientes_Report.getSelectedRows().length > 0) {
            cliente.GetReportCliente();
            cliente.CuotasIntereses();
        }
    }//GEN-LAST:event_Table_clientes_ReportKeyReleased
    ConfigurationVM config;
    private void Btn_ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfiguracionActionPerformed
        // TODO add your handling code here:
        Tabb_Principal.setSelectedIndex(2);
        Btn_Cliente.setEnabled(true);
        Btn_Configuracion.setEnabled(false);
        config = new ConfigurationVM(_radio);
    }//GEN-LAST:event_Btn_ConfiguracionActionPerformed

    private void RadioButtonSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonSolActionPerformed

    private void RadioButton_InteresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_InteresesActionPerformed
        // TODO add your handling code here:
        txf_clienteCuotas.setEnabled(true);
        cliente.CuotasIntereses();
    }//GEN-LAST:event_RadioButton_InteresesActionPerformed

    private void RadioButton_CuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_CuotasActionPerformed
        // TODO add your handling code here:
         txf_clienteCuotas.setEnabled(false);
        cliente.CuotasIntereses();
    }//GEN-LAST:event_RadioButton_CuotasActionPerformed

    private void txf_clientePagosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_clientePagosKeyReleased
        // TODO add your handling code here:
        cliente.CuotasIntereses();
    }//GEN-LAST:event_txf_clientePagosKeyReleased

    private void txf_clientePagosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_clientePagosKeyTyped
        // TODO add your handling code here:
        Objetos.eventos.numberDecimalKeyPress(evt,txf_clientePagos);
    }//GEN-LAST:event_txf_clientePagosKeyTyped

    private void txf_clienteCuotasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_clienteCuotasKeyReleased
        // TODO add your handling code here:
        cliente.CuotasIntereses();
    }//GEN-LAST:event_txf_clienteCuotasKeyReleased

    private void txf_clienteCuotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_clienteCuotasKeyTyped
        // TODO add your handling code here:
        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_txf_clienteCuotasKeyTyped

    private void RadioButtonDollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonDollarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonDollarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B_Cliente;
    private javax.swing.JButton Btn_Agg;
    private javax.swing.JButton Btn_Cli;
    private javax.swing.JButton Btn_Cliente;
    private javax.swing.JButton Btn_Cliente_Paginas1;
    private javax.swing.JButton Btn_Cliente_Paginas2;
    private javax.swing.JButton Btn_Cliente_Paginas3;
    private javax.swing.JButton Btn_Cliente_Paginas4;
    private javax.swing.JButton Btn_Configuracion;
    private javax.swing.JButton Btn_Ventas;
    private javax.swing.JCheckBox ChB_Credito;
    private javax.swing.JLabel Lb_Cli_Ap;
    private javax.swing.JLabel Lb_Cli_Dir;
    private javax.swing.JLabel Lb_Cli_ID;
    private javax.swing.JLabel Lb_Cli_Mail;
    private javax.swing.JLabel Lb_Cli_Nom;
    private javax.swing.JLabel Lb_Cli_Nom1;
    private javax.swing.JLabel Lb_Cli_Nom10;
    private javax.swing.JLabel Lb_Cli_Nom11;
    private javax.swing.JLabel Lb_Cli_Nom12;
    private javax.swing.JLabel Lb_Cli_Nom13;
    private javax.swing.JLabel Lb_Cli_Nom3;
    private javax.swing.JLabel Lb_Cli_Nom5;
    private javax.swing.JLabel Lb_Cli_Nom6;
    private javax.swing.JLabel Lb_Cli_Nom8;
    private javax.swing.JLabel Lb_Cli_Nom9;
    private javax.swing.JLabel Lb_Cli_Tlf;
    private javax.swing.JLabel Lb_Img_Cli;
    private javax.swing.JRadioButton RadioButtonDollar;
    private javax.swing.JRadioButton RadioButtonPeso;
    private javax.swing.JRadioButton RadioButtonSol;
    private javax.swing.JRadioButton RadioButton_Cuotas;
    private javax.swing.JRadioButton RadioButton_Intereses;
    private javax.swing.JSpinner SpinnerPaginas_Clientes;
    private javax.swing.JTabbedPane Tabb_Principal;
    private javax.swing.JTabbedPane TabbedPaneCliente1;
    private javax.swing.JTable Table_clientes;
    private javax.swing.JTable Table_clientes_Report;
    private javax.swing.JTabbedPane Table_clientes_Report1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbReport_Nombre;
    private javax.swing.JLabel lb_CliendePago1;
    private javax.swing.JLabel lb_CliendePago2;
    private javax.swing.JLabel lb_ClienteCuotaMes;
    private javax.swing.JLabel lb_ClienteCuotas;
    private javax.swing.JLabel lb_ClienteDeuda;
    private javax.swing.JLabel lb_ClienteFechaPago;
    private javax.swing.JLabel lb_ClienteIntereses;
    private javax.swing.JLabel lb_ClienteInteresesPago;
    private javax.swing.JLabel lb_ClienteTicket;
    private javax.swing.JLabel lb_ClienteTicketIntereses;
    private javax.swing.JLabel lb_ClienteUltimoPago;
    private javax.swing.JLabel lb_Cliente_Paginas;
    private javax.swing.JLabel lb_FechaIntereses;
    private javax.swing.JLabel lb_ReportsPagos;
    private javax.swing.JTextField tf_Ci;
    private javax.swing.JTextField tf_Nom_CI;
    private javax.swing.JTextField tf_ap_CI;
    private javax.swing.JTextField tf_dir_CI;
    private javax.swing.JTextField tf_mail_CI;
    private javax.swing.JTextField tf_tlf_CI;
    private javax.swing.JTextField txf_clienteCuotas;
    private javax.swing.JTextField txf_clientePagos;
    // End of variables declaration//GEN-END:variables
}
